#include <stdio.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include "property.h"

int createBoard(FILE *fp, Property **propListPtr);
void printProperty(Property p);

/**
int main(int argc, char** argv){
	FILE* fp = fopen(argv[1], "r");
	if (fp == NULL){
		printf("file not opened");
		return 0;
	}
	Property* propList;
	createBoard(fp, &propList);
	printProperty(propList[0]);
	printProperty(propList[1]);
	printProperty(propList[2]);
	printProperty(propList[3]);
	printProperty(propList[4]);
	printProperty(propList[5]);
	printProperty(propList[6]);
	printProperty(propList[7]);
	printProperty(propList[8]);
	printProperty(propList[9]);
	return 0;
}
**/

/**
Creates a board, which is a property*, a list of the properties 
generated by reading the given file. Then propListPtr points to this list
The function returns the number of properties created.
**/
int createBoard(FILE *fp, Property **propListPtr) {
  int numSpaces = 0;
  //Read in number of spaces
  char c[999];
  fgets(c, 999, fp);
  char *p;
  //P should b "Number"
  p = strtok(c, " ,");
  for (int k = 0; k < 3; k++) {
    p = strtok(NULL, " ,.-");
  }
  numSpaces = atoi(p);
  //printf("NumSpaces: %d\n", numSpaces);
  //free(p);
  //free(c); 
  Property *propList = (Property *) malloc(numSpaces * sizeof(Property));
  //l holds the first line, the fgets statements move l up to the first property in the file.
  char *l = (char *) malloc(999 * sizeof(char));
  fgets(l, 999, fp);
  fgets(l, 999, fp);
  fgets(l, 999, fp);
  fgets(l, 999, fp);
  int propsInLastSet = 0;
  int lastIntraset = 0;
  //Creates a new property for each space on the board.
  for (int i = 0; i < numSpaces; i++) {
    propList[i].propNum = i;
    //char* name;
    //int setID;
    //int intrasetID;
    //int price;
    //int houseCost;
    //int hotelCost;
    //int houseRent;
    //int hotelRent;
    //bool owned;
    //bool isGo;
    //int propsInSet;
    //int goPayout;
    //int rent;
    //Determine if go
    propList[i].isGo = false;
    char *d = strtok(l, ",");
    if (strcmp(d, "Go") == 0) {
      propList[i].isGo = true;
    }
    if (propList[i].isGo == true) {
      //printf("Here-1\n");
      propList[i].setID = -1;
      propList[i].intrasetID = -1;
      propList[i].price = -1;
      propList[i].houseCost = -1;
      propList[i].hotelCost = -1;
      propList[i].houseRent = -1;
      propList[i].hotelRent = -1;
      propList[i].owned = false;
      propList[i].propsInSet = -1;
      propList[i].rent = -1;
      propList[i].boardSize = numSpaces;
      propList[i].owningPlayer = -1;
      //Extract go payout and name
      d = strtok(NULL, ",");
      propList[i].goPayout = atoi(d);
      d = strtok(NULL, ",");
      //printf("%s\n", d);
      propList[i].name = (char *) malloc(999 * sizeof(char));
      strcpy(propList[i].name, d);
    }
    //printf("Here0\n");
    //If not go we get the 9 pieces of info we need.
    if (propList[i].isGo == false) {
      propList[i].owningPlayer = -1;
      propList[i].goPayout = -1;
      for (int j = 0; j < 9; j++) {
        //printf("Here1\n");
        d = strtok(NULL, ",");
        if (j == 0) {
          propList[i].setID = atoi(d);
        } else if (j == 1) {
          //printf("Here: %d\n", atoi(d));
          propList[i].intrasetID = atoi(d);
          if (atoi(d) == 0) {
            propsInLastSet = lastIntraset + 1;
            for (int k = 1; k <= propsInLastSet; k++) {
              propList[i - k].propsInSet = propsInLastSet;
            }
          }
          if (i == numSpaces - 1) {
            for (int l = 0; l < atoi(d) + 1; l++) {
              propList[i - l].propsInSet = atoi(d) + 1;
            }
          }
          lastIntraset = atoi(d);
        } else if (j == 2) {
          propList[i].name = (char *) malloc(999 * sizeof(char));
          strcpy(propList[i].name, d);
        } else if (j == 3) {
          propList[i].price = atoi(d);
        } else if (j == 4) {
          propList[i].houseCost = atoi(d);
        } else if (j == 5) {
          propList[i].hotelCost = atoi(d);
        } else if (j == 6) {
          propList[i].rent = atoi(d);
        } else if (j == 7) {
          propList[i].houseRent = atoi(d);
        } else if (j == 8) {
          propList[i].hotelRent = atoi(d);
        } else {
          printf("Ur fucked like forreal\n");
        }
      }
    }
    fgets(l, 999, fp);
  }
  free(l);
  *propListPtr = propList;
  return numSpaces;
}

void printProperty(Property p) {
  printf("Property Number: %d\n", p.propNum);
  printf("Name: %s\n", p.name);
  printf("Set Id: %d\n", p.setID);
  printf("Intraset ID: %d\n", p.intrasetID);
  printf("Properties in set: %d\n", p.propsInSet);
  printf("Property Cost: %d\n", p.price);
  printf("House Cost: %d\n", p.houseCost);
  printf("Hotel Cost: %d\n", p.hotelCost);
  printf("Rent: %d\n", p.rent);
  printf("Rent with House: %d\n", p.houseRent);
  printf("Rent with hotel: %d\n", p.hotelRent);
  printf("Go payout: %d\n\n", p.goPayout);
}